num1 = int(input('Введите первое число: '))
num2 = int(input('Введите второе число: '))
num3 = int(input('Введите третье число: '))
print((num1>0) + (num2>0) + (num3>0))
print((num1<0) + (num2<0) + (num3<0))
